useTabs: false
endOfLine: lf
tabWidth: 4
singleQuote: true
jsxSingleQuote: true
printWidth: 120
semi: false
overrides:
  - files: '*.json'
    options:
      printWidth: 70
  - files: '*.md'
    options:
      printWidth: 70
      useTabs: false
      trailingComma: none
      arrowParens: avoid
      proseWrap: never
  - files: '*.yaml'
    options:
      tabWidth: 2
